let s:currentpath=expand('<sfile>:p:h')
execute 'source '.fnameescape(s:currentpath . '/init-Vundle.vim')
execute 'source '.fnameescape(s:currentpath . '/init-YouCompleteMe.vim')
execute 'source '.fnameescape(s:currentpath . '/init-DoxygenToolkit.vim')
execute 'source '.fnameescape(s:currentpath . '/init-doxygen.vim')
execute 'source '.fnameescape(s:currentpath . '/init-clang-format.vim')
execute 'source '.fnameescape(s:currentpath . '/init-vim-javascript.vim')
execute 'source '.fnameescape(s:currentpath . '/init-vim-jsbeautify.vim')
execute 'source '.fnameescape(s:currentpath . '/basic.vim')
execute 'source '.fnameescape(s:currentpath . '/init-supertab.vim')
execute 'source '.fnameescape(s:currentpath . '/init-vim-jsx.vim')
execute 'source '.fnameescape(s:currentpath . '/init-pathogen.vim')
execute 'source '.fnameescape(s:currentpath . '/init-python-mode.vim')
